config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sessions#new'

  get '/', to: "teams#index"
  get '/signup', to: "users#new"
  get '/new_team', to: "teams#new"
  post '/new_team', to: "teams#create"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/index123', to: 'players#index'
  post '/delete_player_from_roster', to: 'teams#delete_from_roster'
  post '/rename_team', to: 'teams#rename_team'

  get '/players', to: 'teams#add_player'
  post '/players', to: 'teams#add_to_roster'
  post '/players_team', to: 'teams#set_data'

  post '/', to: 'teams#destroy'

  get '/stats', to: 'stats#stats'
  
  resources :teams, only: [:index, :create]
  resources :players, only: [:index]
  resources :users, only: [:create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FantasyFootballDraftApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <header>Fantasy Football Draft Toolkit</header>
<body>
  <nav>
    <ul>
      <% if current_user %>
        <p><%= link_to "Log Out", logout_path %></p>
        <p><%= link_to "Home", teams_path %></p>
        <p><%= link_to "Add Team", new_team_path %></p>
        <p><%= link_to "Stat Leaders", stats_path %></p>
        <p><%= link_to "Add Players", players_path%></p>
      <% else %>
        <p><%= link_to "Sign Up", signup_path %></p>
        <p><%= link_to "Log In", login_path %></p>
        <p><%= link_to "Home", teams_path %></p>
      <% end %>
    </ul>
  </nav>

    <strong>
      <% flash.each do |name, msg| %>
       <%= content_tag :div, msg.html_safe %>
      <% end %>
    </strong>


    <%= yield %>
  </body>
</html>